### ISSUE TITLE
Allow unfree

### ISSUE THREAD

**Issue by fliiiix** [markuskowa/nix-system#2]
Where or how would one set `allowUnfree = true;` in this kind of setup?

**Comment by markuskowa** [comment]
> Where or how would one set `allowUnfree = true;` in this kind of setup?

How are you using this repository? What components of this repo are you trying to use?

**Comment by fliiiix** [comment]
I tried to copy the setup for my own packages to have my own package tree but some of my packages are unfree and im struggling to understand how something like this (https://stackoverflow.com/questions/77585228/how-to-allow-unfree-packages-in-nix-for-each-situation-nixos-nix-nix-wit) would map to the flake.nix

**Comment by fliiiix** [comment]
Ahh i figured it out where to add the config set 

```
  outputs = { self, nixpkgs }: let
    config = {
      allowUnfree = true;
    };
    forAllSystems = func: nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ] (system: func (import nixpkgs { inherit system config; }));
  in {
    overlays.default = import ./default.nix;

    packages = forAllSystems (pkgs: import ./packages.nix pkgs);
  };
```
